---
title: "Task 3"
author: "Yujia Wang"
date: "12/8/2021"
output:
  pdf_document: 
          latex_engine: xelatex
  html_document: default
---


## Task 3: sentence-level analysis

```{r}
# library some packages
#install.packages("devtools")
library(devtools)
#devtools::install_github("Truenumbers/tnum/tnum")
library(tnum)
library(knitr)

# prepare for the environment
tnum.authorize("mssp1.bu.edu")
#tnum.setSpace("test2")
#tnum.getSpace()
tnum.setSpace("test3")
tnum.getSpace()

# prepare for the book text
alice3 <- gutenberg_download(gutenberg_id = 11)
alice3$text <- gsub("’","'",alice3$text)
alice3$text <- gsub('“','"',alice3$text)
alice3$text <- gsub('”','"',alice3$text)
alice3$text <- gsub('—','',alice3$text)
alice3$text <- gsub('_','',alice3$text)
alice3$text <- gsub("‘","'",alice3$text)

writeLines(alice3$text, "alice_text.txt")
alice4 <- readLines("alice_text.txt")
show(alice4)

# source TN
source("Book2TN-v6A-1.R")
```


```{r}
# ingest my book
#tnBooksFromLines(alice4, "carroll/alice")

# check the book is in the environment
tnum.getDBPathList(taxonomy = "subject", levels=2)
#tnum.getDBPathList(taxonomy = "subject", levels=1)
```

```{r}
# query section
query_section <- tnum.query('carroll/alice/section# has text',max=1000)  
section <- tnum.objectsToDf(query_section)

# clear up section
category <- section %>% 
            separate(
              col = subject,
              into = c("carroll", "alice","section","paragraph","sentence"), 
              sep = "/") 
category <- category %>%
            select(section,paragraph,sentence,string.value)
colnames(category)[which(names(category) == "string.value")] <- "string"

# simplify category
category_clean <- category %>%
                  mutate_at(c(1,2,3),~str_extract_all(.,"\\d+") %>% 
                  unlist() %>%
                  as.numeric())
category_clean[13:55,1] <- 1
category_clean[56:98,1] <- 2
category_clean[99:153,1] <- 3
category_clean[154:209,1] <- 4
category_clean[210:271,1] <- 5
category_clean[272:366,1] <- 6
category_clean[367:456,1] <- 7
category_clean[457:531,1] <- 8
category_clean[532:616,1] <- 9
category_clean[617:689,1] <- 10
category_clean[690:765,1] <- 11
category_clean[766:828,1] <- 12
```


```{r}
# sentimentr
library(sentimentr)

# filter sentiment
sentiment <- category_clean %>% 
             get_sentences() %>% 
             sentiment() %>% 
             mutate(polarity_level = ifelse(sentiment<0.2, "Negative",
                                  ifelse(sentiment>0.2,"Positive","Neutral")))

sentiment$element_id <- as.numeric(sentiment$element_id)
sentiment$sentiment <- as.numeric(sentiment$sentiment)

# seperate sentiment
sentiment_neg <- sentiment %>% 
                 filter(polarity_level == "Negative") 
sentiment_pos <- sentiment %>% 
                 filter(polarity_level == "Positive") 
```


```{r}
# visualization 1: trend of sentiment          
plot(sentiment)
```

```{r}
# visualization 2: average sentiment density plot
category_clean %>% 
     get_sentences() %>% 
     sentiment_by(by = NULL) %>% 
     ggplot() + 
     geom_density(aes(ave_sentiment)) 
```

```{r}
# visualization 3: negative and positive line plot
ggplot() + 
       geom_line(data=sentiment_neg, aes(x=element_id, y=sentiment),color="brown3") +
       geom_line(data=sentiment_pos, aes(x=element_id, y=sentiment),color="skyblue3") +
       ylim(-1.5, 1) +
       geom_hline(yintercept=0.2, linetype="dashed", color = "black")
```

```{r}
# visualization 4: sentiment in each chapter
ggplot(data=sentiment) + 
  geom_point(aes(x= element_id, y = sentiment, color = section)) + 
  theme(legend.position = "right") +
  facet_wrap(~section,c(4)) +
  geom_hline(yintercept=0, linetype="dashed", color = "black")
```


### Compare task 3 with task 2

```{r}
# clean up the data
compare_data <- alice3 %>%
          select(-gutenberg_id) %>%
          mutate(linenumber = row_number(),
          chapter = cumsum(str_detect(text, 
                                      regex("^chapter [\\divxlc]",
                                      ignore_case = TRUE)))) %>%
          filter(linenumber >= 30) %>%
          ungroup()
compare_data <- compare_data %>%
                unnest_tokens(word, text)

# use bing method
compare <- compare_data %>%
  inner_join(get_sentiments("bing")) %>%
  count(index = chapter, sentiment) %>%
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative) %>%
  mutate(method = "Bing et al.")

compare_plot1 <- ggplot(compare, aes(index, sentiment)) +
  geom_col(show.legend = FALSE)

# task 2 result
alice_sentiment <- alice2 %>%
  inner_join(get_sentiments("bing")) %>%
  count(index = linenumber %/% 80, sentiment) %>%
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative)

compare_plot2 <- ggplot(alice_sentiment, aes(index, sentiment)) +
  geom_col(show.legend = FALSE)
```

```{r}
# visualization 4: compare task 3 with task 2
ggarrange(compare_plot1, compare_plot2, heights = c(2, 0.7),
          ncol = 1, nrow = 2)
```


## Extra credit: character-level analysis
xxxx

```{r}
# select 1 character
sentiment$character <- ifelse(str_detect(sentiment$string,"Alice", negate = FALSE)==TRUE, "Alice",ifelse(str_detect(sentiment$string,"Queen", negate = FALSE)==TRUE, "Queen",ifelse(str_detect(sentiment$string,"King", negate = FALSE)==TRUE, "King",ifelse(str_detect(sentiment$string,"Turtle", negate = FALSE)==TRUE, "Turtle",ifelse(str_detect(sentiment$string,"Hatter", negate = FALSE)==TRUE,"Hatter",ifelse(str_detect(sentiment$string,"Gryphon", negate = FALSE)==TRUE,"Gryphon", ""))))))
sentiment1 <- filter(sentiment, character != "")

# select 2 characters
sentiment$character2 <- ifelse(str_detect(sentiment$string,"Queen", negate = FALSE)==TRUE & sentiment$character == "Alice", "A&Q",                                     ifelse(str_detect(sentiment$string,"King", negate = FALSE)==TRUE & sentiment$character == "Alice", "A&K",                                            ifelse(str_detect(sentiment$string,"Turtle", negate = FALSE)==TRUE & sentiment$character == "Alice", "A&T",                                                  ifelse(str_detect(sentiment$string,"Hatter", negate = FALSE)==TRUE & sentiment$character == "Alice", "A&H", ifelse(str_detect(sentiment$string,"Gryphon", negate = FALSE)==TRUE & sentiment$character == "Alice","A&G", "")))))
sentiment2 <- filter(sentiment, character2 != "")

```

```{r}
# visualization 5:
ggplot(data=sentiment1) + 
  geom_histogram(aes(sentiment, color=character)) +
  facet_wrap(~character)
```

```{r}
# visualization 6:
ggplot(data=sentiment2) + 
  geom_histogram(aes(sentiment, color=character2)) +
  facet_wrap(~character2)
```


## Reference 

Haviland Wright, tnum - instructions and examples - v5.Rmd
[https://www.gutenberg.org/ebooks/11](https://www.gutenberg.org/ebooks/11)
[https://www.r-bloggers.com/2020/04/sentiment-analysis-in-r-with-sentimentr-that-handles-negation-valence-shifters/](https://www.r-bloggers.com/2020/04/sentiment-analysis-in-r-with-sentimentr-that-handles-negation-valence-shifters/)





